# Generated by Django 3.2.16 on 2022-12-04 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rewies',
            new_name='Review',
        ),
    ]
